spring:
  application:
    name: offer-service
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    com.retail.ai.offer.service: DEBUG

