PRODUCTS = [
    {
        "id": "sku-100",
        "name": "Performance Running Shoes",
        "category": "footwear",
        "price": 89.99,
        "description": "Lightweight daily trainer built for comfort.",
        "text": "Performance Running Shoes lightweight running comfort sport footwear everyday trainer",
    },
    {
        "id": "sku-101",
        "name": "Sports Crew Socks",
        "category": "accessories",
        "price": 12.99,
        "description": "Cushioned socks that pair well with training shoes.",
        "text": "Sports Crew Socks accessory running comfort cushioned bundle training",
    },
    {
        "id": "sku-102",
        "name": "Hydration Bottle",
        "category": "accessories",
        "price": 18.50,
        "description": "Insulated bottle for workouts and everyday use.",
        "text": "Hydration Bottle fitness workout insulated bundle accessory training",
    },
    {
        "id": "sku-103",
        "name": "Yoga Mat",
        "category": "fitness",
        "price": 29.00,
        "description": "Non-slip mat for home workouts and stretching.",
        "text": "Yoga Mat fitness home wellness stretching non-slip workout",
    },
    {
        "id": "sku-104",
        "name": "Wireless Earbuds",
        "category": "electronics",
        "price": 59.99,
        "description": "Sweat-resistant earbuds for workouts.",
        "text": "Wireless Earbuds electronics music portable workout sweat-resistant",
    },
    {
        "id": "sku-105",
        "name": "Compression Shirt",
        "category": "apparel",
        "price": 34.99,
        "description": "Breathable training shirt with a close fit.",
        "text": "Compression Shirt apparel sport running breathable training",
    },
]
